export enum Permission {
    Category_Add = 1,
    Category_Delete = 2,
    Category_Update = 4,
    Category_Get = 3,
    User_Add = 6,
    User_Delete = 8,
    User_Update =7,
    User_Get = 5,
    Product_Add = 9,
    Product_Delete = 11,
    Product_Update = 10,
    Product_Get = 12,
    Permission_Update = 13,
}